### PR TITLE
Adding s2i environment file

### LINKED ISSUE #53: build error on OpenShift 4.5 with .net template
when I build this sample I get following error
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source...
error: DOTNET_STARTUP_PROJECT has no project file
You can specify the startup project by adding an '.s2i/environment' file to the source repository.
The source repository contains the following projects:
- app/app.csproj
Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=app/app.csproj.
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1

oc new-app dotnet:3.1~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-3.1 --context-dir app
works!

reason:
context-dir is set! not explicitly mentioned in ReadMe...

### PR DESCRIPTION
**Pull request by jtpollard**
Fixes #53 - App failing to auto build & deploy in OpenShift 4.5+ via "from Git" option.

Signed-off-by: Jamie Pollard <jamie@redhat.com>

### CODE REVIEW

**Comment by jtpollard** [comment]
Fixes #53

**Comment by tmds** [comment]
One thing we want people to learn when using this repository, is that they should set working-dir or DOTNET_STARTUP_PROJECT.

When we include this in the ` .s2i/environment` the repo automagically works, but they don't learn why.

That's why I prefer not to not merge this and mention it explicitly in the documentation instead, see https://github.com/redhat-developer/s2i-dotnetcore-ex/issues/53#issuecomment-735613948.

cc @aslicerh

**Comment by jtpollard** [comment]
Hi @tmds @aslicerh  - the issue with this approach is that this app is one of the featured apps in the OpenShift 4 samples catalogue. It is a really poor user experience that someone can provision a cluster with just a few commands, choose this as their first app to deploy, only to face errors and have to troubleshoot the deployment. This small thing, if their first experience, could easily lead to people thinking OpenShift is "just too hard".
 
Might I also suggest that learning through frustration is not the best approach, better to provide a complete working example repo that people can diff against when they are trying to establish why their own app isn't working with s2i.

If you are very against this, then might I suggest a fork or similar, so that users of the OpenShift samples catalogue get a clean experience, but the default project on GitHub does not include the file.

**Comment by tmds** [comment]
This should worked when created as an OpenShift example. The metadata includes `app` must be used for `context-dir`:

https://github.com/redhat-developer/s2i-dotnetcore/blob/4c2802608b12a41546e4436c386a94887c60acf9/dotnet_imagestreams.json#L31

**Comment by jtpollard** [comment]
@tmds you're right - it does work now... when I tried with OpenShift 4.5 a few weeks back, it didn't work on the "happy path" experience, hence me raising this as it fixed the issue. Thanks, I'll close off.

**Comment by tmds** [comment]
@jtpollard thanks for looking into this. We definitely care about users having a good experience when using .NET on OpenShift.

**Pull request closed without merging**
