### PR TITLE
Updated to support .NET core 1.0 release

### PR DESCRIPTION
**Pull request by sabre1041**
Updated example application to support .NET Core 1.0 release.

Tested and validated against newly released RHEL s2i builder (`registry.access.redhat.com/dotnet/dotnetcore-10-rhel7`)

### CODE REVIEW

**Comment by luciddreamz** [comment]
@jawnsy Please merge

**Comment by bparees** [comment]
has it been confirmed that this still works w/ the community asp.net image?

**Comment by bparees** [comment]
also the commits should be squashed.

**Comment by sabre1041** [comment]
@bparees i havent yet updated/verified the upstream image. I'll do so today and squash the commits on this PR

**Comment by bparees** [comment]
thanks @sabre1041

**Comment by sabre1041** [comment]
@bparees Commits in this PR have been squashed. Upstream [s2i-aspnet](https://github.com/openshift-s2i/s2i-aspnet) image has been updated and the application in this PR was tested against it and in included in a new [PR](https://github.com/openshift-s2i/s2i-aspnet/pull/25)

**Comment by bparees** [comment]
thanks

**Pull request merged**
